/* This is stub file for gapi.client.some-name definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: undefined

gapi.load('client', () => {
    /** now we can use gapi.client */
    gapi.client.load('some-name', 'v1', () => {
        /** now we can use gapi.client.some-name */

        run();
    });

    async function run() {
        await gapi.client.some-name.firstResource.firstMethod();
    }
});
