version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
      timezone: 'Australia/Sydney'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
      timezone: 'Australia/Sydney'
groups:
  dedent:
    patterns:
      - 'dedent'
      - '@types/dedent'
  dot:
    patterns:
      - 'dot'
      - '@types/dot'
  lodash:
    patterns:
      - 'lodash'
      - '@types/lodash'
  n-readlines:
    patterns:
      - 'n-readlines'
      - '@types/n-readlines'
  validate-npm-package-name:
    patterns:
      - 'validate-npm-package-name'
      - '@types/validate-npm-package-name'
  dt-stuff:
    patterns:
      - '@definitelytyped/*'
