version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
      timezone: 'Australia/Sydney'
    labels:
      - 'dependencies'
      - 'automerge-kodiak'
