/* Type definitions for non-npm package Business Profile Performance API v1 1.0 */
// Project: https://developers.google.com/my-business/
// Definitions by: Maxim Mazurok <https://github.com/Maxim-Mazurok>
//                 Nick Amoscato <https://github.com/namoscato>
//                 Declan Vong <https://github.com/declanvong>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.8

// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator
// Generated from: https://businessprofileperformance.googleapis.com/$discovery/rest?version=v1
// Revision: 20220730

/// <reference types="gapi.client" />

declare namespace gapi.client {
    /** Load Business Profile Performance API v1 */
    function load(name: "businessprofileperformance", version: "v1"): PromiseLike<void>;
    function load(name: "businessprofileperformance", version: "v1", callback: () => any): void;

    namespace businessprofileperformance {
        interface Date {
            /** Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant. */
            day?: number;
            /** Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day. */
            month?: number;
            /** Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year. */
            year?: number;
        }
        interface DatedValue {
            /** The date that the datapoint corresponds to. This represents a month value if the day field is not set. */
            date?: Date;
            /** The value of the datapoint. */
            value?: string;
        }
        interface GetDailyMetricsTimeSeriesResponse {
            /** The daily time series. */
            timeSeries?: TimeSeries;
        }
        interface InsightsValue {
            /** Represents the threshold below which the actual value falls. */
            threshold?: string;
            /** Represents the actual value. */
            value?: string;
        }
        interface ListSearchKeywordImpressionsMonthlyResponse {
            /**
             * A token indicating the last paginated result returned. This can be used by succeeding requests to get the next "page" of keywords. It will only be present when there are more
             * results to be returned.
             */
            nextPageToken?: string;
            /** Search terms which have been used to find a business. */
            searchKeywordsCounts?: SearchKeywordCount[];
        }
        interface SearchKeywordCount {
            /**
             * One of either: 1) The sum of the number of unique users that used the keyword in a month, aggregated for each month requested. 2) A threshold that indicates that the actual value is
             * below this threshold.
             */
            insightsValue?: InsightsValue;
            /** The lower-cased string that the user entered. */
            searchKeyword?: string;
        }
        interface TimeSeries {
            /** List of datapoints in the timeseries, where each datapoint is a date-value pair. */
            datedValues?: DatedValue[];
        }
        interface MonthlyResource {
            // tslint:disable:max-line-length
            /**
             * Returns the search keywords used to find a business in search or maps. Each search keyword is accompanied by impressions which are aggregated on a monthly basis. Example request:
             * `GET
             * https://businessprofileperformance.googleapis.com/v1/locations/12345/searchkeywords/impressions/monthly?monthly_range.start_month.year=2022&monthly_range.start_month.month=1&monthly_range.end_month.year=2022&monthly_range.end_month.month=3`
             */
            // tslint:enable:max-line-length
            list(request?: {
                /** V1 error format. */
                "$.xgafv"?: string;
                /** OAuth access token. */
                access_token?: string;
                /** Data format for response. */
                alt?: string;
                /** JSONP */
                callback?: string;
                /** Selector specifying which fields to include in a partial response. */
                fields?: string;
                /** API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token. */
                key?: string;
                /** Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant. */
                "monthlyRange.endMonth.day"?: number;
                /** Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day. */
                "monthlyRange.endMonth.month"?: number;
                /** Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year. */
                "monthlyRange.endMonth.year"?: number;
                /** Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant. */
                "monthlyRange.startMonth.day"?: number;
                /** Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day. */
                "monthlyRange.startMonth.month"?: number;
                /** Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year. */
                "monthlyRange.startMonth.year"?: number;
                /** OAuth 2.0 token for the current user. */
                oauth_token?: string;
                /** Optional. The number of results requested. The default page size is 100. Page size can be set to a maximum of 100. */
                pageSize?: number;
                /** Optional. A token indicating the next paginated result to be returned. */
                pageToken?: string;
                /** Required. The location for which the time series should be fetched. Format: locations/{location_id} where location_id is an unobfuscated listing id. */
                parent: string;
                /** Returns response with indentations and line breaks. */
                prettyPrint?: boolean;
                /** Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. */
                quotaUser?: string;
                /** Upload protocol for media (e.g. "raw", "multipart"). */
                upload_protocol?: string;
                /** Legacy upload protocol for media (e.g. "media", "multipart"). */
                uploadType?: string;
            }): Request<ListSearchKeywordImpressionsMonthlyResponse>;
        }
        interface ImpressionsResource {
            monthly: MonthlyResource;
        }
        interface SearchkeywordsResource {
            impressions: ImpressionsResource;
        }
        interface LocationsResource {
            // tslint:disable:max-line-length
            /**
             * Returns the values for each date from a given time range that are associated with the specific daily metric. Example request: `GET
             * https://businessprofileperformance.googleapis.com/v1/locations/12345:getDailyMetricsTimeSeries?dailyMetric=WEBSITE_CLICKS&daily_range.start_date.year=2022&daily_range.start_date.month=1&daily_range.start_date.day=1&daily_range.end_date.year=2022&daily_range.end_date.month=3&daily_range.end_date.day=31`
             */
            // tslint:enable:max-line-length
            getDailyMetricsTimeSeries(request?: {
                /** V1 error format. */
                "$.xgafv"?: string;
                /** OAuth access token. */
                access_token?: string;
                /** Data format for response. */
                alt?: string;
                /** JSONP */
                callback?: string;
                /** Required. The metric to retrieve time series. */
                dailyMetric?: string;
                /** Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant. */
                "dailyRange.endDate.day"?: number;
                /** Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day. */
                "dailyRange.endDate.month"?: number;
                /** Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year. */
                "dailyRange.endDate.year"?: number;
                /** Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant. */
                "dailyRange.startDate.day"?: number;
                /** Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day. */
                "dailyRange.startDate.month"?: number;
                /** Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year. */
                "dailyRange.startDate.year"?: number;
                /** Represents the day of the week. Eg: MONDAY. */
                "dailySubEntityType.dayOfWeek"?: string;
                /** Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time. */
                "dailySubEntityType.timeOfDay.hours"?: number;
                /** Minutes of hour of day. Must be from 0 to 59. */
                "dailySubEntityType.timeOfDay.minutes"?: number;
                /** Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999. */
                "dailySubEntityType.timeOfDay.nanos"?: number;
                /** Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds. */
                "dailySubEntityType.timeOfDay.seconds"?: number;
                /** Selector specifying which fields to include in a partial response. */
                fields?: string;
                /** API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token. */
                key?: string;
                /** Required. The location for which the time series should be fetched. Format: locations/{location_id} where location_id is an unobfuscated listing id. */
                name: string;
                /** OAuth 2.0 token for the current user. */
                oauth_token?: string;
                /** Returns response with indentations and line breaks. */
                prettyPrint?: boolean;
                /** Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. */
                quotaUser?: string;
                /** Upload protocol for media (e.g. "raw", "multipart"). */
                upload_protocol?: string;
                /** Legacy upload protocol for media (e.g. "media", "multipart"). */
                uploadType?: string;
            }): Request<GetDailyMetricsTimeSeriesResponse>;
            searchkeywords: SearchkeywordsResource;
        }

        const locations: LocationsResource;
    }
}
