/* This is stub file for gapi.client.gmailpostmastertools-v1 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20250529

gapi.load('client', async () => {
  /** now we can use gapi.client */

  await gapi.client.load(
    'https://gmailpostmastertools.googleapis.com/$discovery/rest?version=v1',
  );
  /** now we can use gapi.client.gmailpostmastertools */

  void run();

  async function run() {
    /** Gets a specific domain registered by the client. Returns NOT_FOUND if the domain does not exist. */
    await gapi.client.gmailpostmastertools.domains.get({
      name: 'Test string',
    });
    /** Lists the domains that have been registered by the client. The order of domains in the response is unspecified and non-deterministic. Newly created domains will not necessarily be added to the end of this list. */
    await gapi.client.gmailpostmastertools.domains.list({
      pageSize: 42,
      pageToken: 'Test string',
    });
    /** Get traffic statistics for a domain on a specific date. Returns PERMISSION_DENIED if user does not have permission to access TrafficStats for the domain. */
    await gapi.client.gmailpostmastertools.domains.trafficStats.get({
      name: 'Test string',
    });
    /** List traffic statistics for all available days. Returns PERMISSION_DENIED if user does not have permission to access TrafficStats for the domain. */
    await gapi.client.gmailpostmastertools.domains.trafficStats.list({
      'endDate.day': 42,
      'endDate.month': 42,
      'endDate.year': 42,
      pageSize: 42,
      pageToken: 'Test string',
      parent: 'Test string',
      'startDate.day': 42,
      'startDate.month': 42,
      'startDate.year': 42,
    });
  }
});
