/* This is stub file for gapi.client.sts-v1 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20230521

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://sts.googleapis.com/$discovery/rest?version=v1');
    /** now we can use gapi.client.sts */

    run();

    async function run() {
        /** Gets information about a Google OAuth 2.0 access token issued by the Google Cloud [Security Token Service API](https://cloud.google.com/iam/docs/reference/sts/rest). */
        await gapi.client.sts.v1.introspect({
        }, {
            token: "Test string",
            tokenTypeHint: "Test string",
        });
        /**
         * Exchanges a credential that represents the resource owner's authorization for a Google-generated [OAuth 2.0 access token] (https://www.rfc-editor.org/rfc/rfc6749#section-5) or
         * [refreshes an accesstoken] (https://www.rfc-editor.org/rfc/rfc6749#section-6) following [the OAuth 2.0 authorization framework] (https://tools.ietf.org/html/rfc8693) The credential can
         * be one of the following: - An authorization code issued by the workforce identity federation authorization endpoint - A [refresh
         * token](https://www.rfc-editor.org/rfc/rfc6749#section-10.4) issued by this endpoint This endpoint is only meant to be called by the Google Cloud CLI. Also note that this API only
         * accepts the authorization code issued for workforce pools.
         */
        await gapi.client.sts.v1.oauthtoken({
        }, {
            clientId: "Test string",
            code: "Test string",
            codeVerifier: "Test string",
            grantType: "Test string",
            redirectUri: "Test string",
            refreshToken: "Test string",
            scope: "Test string",
        });
        /**
         * Exchanges a credential for a Google OAuth 2.0 access token. The token asserts an external identity within an identity pool, or it applies a Credential Access Boundary to a Google access
         * token. Note that workforce pools do not support Credential Access Boundaries. When you call this method, do not send the `Authorization` HTTP header in the request. This method does not
         * require the `Authorization` header, and using the header can cause the request to fail.
         */
        await gapi.client.sts.v1.token({
        }, {
            audience: "Test string",
            grantType: "Test string",
            options: "Test string",
            requestedTokenType: "Test string",
            scope: "Test string",
            subjectToken: "Test string",
            subjectTokenType: "Test string",
        });
    }
});
