/* This is stub file for gapi.client.apigateway-v1 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20220908

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://apigateway.googleapis.com/$discovery/rest?version=v1');
    /** now we can use gapi.client.apigateway */

    /** don't forget to authenticate your client before sending any request to resources: */
    /** declare client_id registered in Google Developers Console */
    const client_id = '<<PUT YOUR CLIENT ID HERE>>';
    const scope = [
        /** See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account. */
        'https://www.googleapis.com/auth/cloud-platform',
    ];
    const immediate = false;
    gapi.auth.authorize({ client_id, scope, immediate }, authResult => {
        if (authResult && !authResult.error) {
            /** handle successful authorization */
            run();
        } else {
            /** handle authorization error */
        }
    });

    async function run() {
        /** Gets information about a location. */
        await gapi.client.apigateway.projects.locations.get({
            name: "Test string",
        });
        /** Lists information about the supported locations for this service. */
        await gapi.client.apigateway.projects.locations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /** Creates a new Api in a given project and location. */
        await gapi.client.apigateway.projects.locations.apis.create({
            apiId: "Test string",
            parent: "Test string",
        }, {
            createTime: "Test string",
            displayName: "Test string",
            labels: {
                A: "Test string"
            },
            managedService: "Test string",
            name: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Deletes a single Api. */
        await gapi.client.apigateway.projects.locations.apis.delete({
            name: "Test string",
        });
        /** Gets details of a single Api. */
        await gapi.client.apigateway.projects.locations.apis.get({
            name: "Test string",
        });
        /** Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set. */
        await gapi.client.apigateway.projects.locations.apis.getIamPolicy({
            "options.requestedPolicyVersion": 42,
            resource: "Test string",
        });
        /** Lists Apis in a given project and location. */
        await gapi.client.apigateway.projects.locations.apis.list({
            filter: "Test string",
            orderBy: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /** Updates the parameters of a single Api. */
        await gapi.client.apigateway.projects.locations.apis.patch({
            name: "Test string",
            updateMask: "Test string",
        }, {
            createTime: "Test string",
            displayName: "Test string",
            labels: {
                A: "Test string"
            },
            managedService: "Test string",
            name: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors. */
        await gapi.client.apigateway.projects.locations.apis.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                auditConfigs: [
                    {
                        auditLogConfigs: [
                            {
                                exemptedMembers: [
                                    "Test string"
                                ],
                                logType: "Test string",
                            }
                        ],
                        service: "Test string",
                    }
                ],
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
            updateMask: "Test string",
        });
        /**
         * Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This
         * operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may "fail open" without warning.
         */
        await gapi.client.apigateway.projects.locations.apis.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /** Creates a new ApiConfig in a given project and location. */
        await gapi.client.apigateway.projects.locations.apis.configs.create({
            apiConfigId: "Test string",
            parent: "Test string",
        }, {
            createTime: "Test string",
            displayName: "Test string",
            gatewayServiceAccount: "Test string",
            grpcServices: [
                {
                    fileDescriptorSet: {
                        contents: "Test string",
                        path: "Test string",
                    },
                    source: [
                        {
                            contents: "Test string",
                            path: "Test string",
                        }
                    ],
                }
            ],
            labels: {
                A: "Test string"
            },
            managedServiceConfigs: [
                {
                    contents: "Test string",
                    path: "Test string",
                }
            ],
            name: "Test string",
            openapiDocuments: [
                {
                    document: {
                        contents: "Test string",
                        path: "Test string",
                    },
                }
            ],
            serviceConfigId: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Deletes a single ApiConfig. */
        await gapi.client.apigateway.projects.locations.apis.configs.delete({
            name: "Test string",
        });
        /** Gets details of a single ApiConfig. */
        await gapi.client.apigateway.projects.locations.apis.configs.get({
            name: "Test string",
            view: "Test string",
        });
        /** Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set. */
        await gapi.client.apigateway.projects.locations.apis.configs.getIamPolicy({
            "options.requestedPolicyVersion": 42,
            resource: "Test string",
        });
        /** Lists ApiConfigs in a given project and location. */
        await gapi.client.apigateway.projects.locations.apis.configs.list({
            filter: "Test string",
            orderBy: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /** Updates the parameters of a single ApiConfig. */
        await gapi.client.apigateway.projects.locations.apis.configs.patch({
            name: "Test string",
            updateMask: "Test string",
        }, {
            createTime: "Test string",
            displayName: "Test string",
            gatewayServiceAccount: "Test string",
            grpcServices: [
                {
                    fileDescriptorSet: {
                        contents: "Test string",
                        path: "Test string",
                    },
                    source: [
                        {
                            contents: "Test string",
                            path: "Test string",
                        }
                    ],
                }
            ],
            labels: {
                A: "Test string"
            },
            managedServiceConfigs: [
                {
                    contents: "Test string",
                    path: "Test string",
                }
            ],
            name: "Test string",
            openapiDocuments: [
                {
                    document: {
                        contents: "Test string",
                        path: "Test string",
                    },
                }
            ],
            serviceConfigId: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors. */
        await gapi.client.apigateway.projects.locations.apis.configs.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                auditConfigs: [
                    {
                        auditLogConfigs: [
                            {
                                exemptedMembers: [
                                    "Test string"
                                ],
                                logType: "Test string",
                            }
                        ],
                        service: "Test string",
                    }
                ],
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
            updateMask: "Test string",
        });
        /**
         * Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This
         * operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may "fail open" without warning.
         */
        await gapi.client.apigateway.projects.locations.apis.configs.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /** Creates a new Gateway in a given project and location. */
        await gapi.client.apigateway.projects.locations.gateways.create({
            gatewayId: "Test string",
            parent: "Test string",
        }, {
            apiConfig: "Test string",
            createTime: "Test string",
            defaultHostname: "Test string",
            displayName: "Test string",
            labels: {
                A: "Test string"
            },
            name: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Deletes a single Gateway. */
        await gapi.client.apigateway.projects.locations.gateways.delete({
            name: "Test string",
        });
        /** Gets details of a single Gateway. */
        await gapi.client.apigateway.projects.locations.gateways.get({
            name: "Test string",
        });
        /** Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set. */
        await gapi.client.apigateway.projects.locations.gateways.getIamPolicy({
            "options.requestedPolicyVersion": 42,
            resource: "Test string",
        });
        /** Lists Gateways in a given project and location. */
        await gapi.client.apigateway.projects.locations.gateways.list({
            filter: "Test string",
            orderBy: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /** Updates the parameters of a single Gateway. */
        await gapi.client.apigateway.projects.locations.gateways.patch({
            name: "Test string",
            updateMask: "Test string",
        }, {
            apiConfig: "Test string",
            createTime: "Test string",
            defaultHostname: "Test string",
            displayName: "Test string",
            labels: {
                A: "Test string"
            },
            name: "Test string",
            state: "Test string",
            updateTime: "Test string",
        });
        /** Sets the access control policy on the specified resource. Replaces any existing policy. Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED` errors. */
        await gapi.client.apigateway.projects.locations.gateways.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                auditConfigs: [
                    {
                        auditLogConfigs: [
                            {
                                exemptedMembers: [
                                    "Test string"
                                ],
                                logType: "Test string",
                            }
                        ],
                        service: "Test string",
                    }
                ],
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
            updateMask: "Test string",
        });
        /**
         * Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a `NOT_FOUND` error. Note: This
         * operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may "fail open" without warning.
         */
        await gapi.client.apigateway.projects.locations.gateways.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /**
         * Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this
         * method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation
         * completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of
         * 1, corresponding to `Code.CANCELLED`.
         */
        await gapi.client.apigateway.projects.locations.operations.cancel({
            name: "Test string",
        }, {
        });
        /**
         * Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support
         * this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
         */
        await gapi.client.apigateway.projects.locations.operations.delete({
            name: "Test string",
        });
        /** Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. */
        await gapi.client.apigateway.projects.locations.operations.get({
            name: "Test string",
        });
        /**
         * Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to
         * override the binding to use different resource name schemes, such as `users/*‍/operations`. To override the binding, API services can add a binding such as
         * `"/v1/{name=users/*}/operations"` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must
         * ensure the name binding is the parent resource, without the operations collection id.
         */
        await gapi.client.apigateway.projects.locations.operations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
    }
});
