/* This is stub file for gapi.client.cloudlocationfinder-v1alpha definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20260709

gapi.load('client', async () => {
  /** now we can use gapi.client */

  await gapi.client.load(
    'https://cloudlocationfinder.googleapis.com/$discovery/rest?version=v1alpha',
  );
  /** now we can use gapi.client.cloudlocationfinder */

  /** don't forget to authenticate your client before sending any request to resources: */
  /** declare client_id registered in Google Developers Console */
  const client_id = '<<PUT YOUR CLIENT ID HERE>>';
  const scope = [
    /** See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account. */
    'https://www.googleapis.com/auth/cloud-platform',
  ];
  const immediate = false;
  gapi.auth.authorize({client_id, scope, immediate}, authResult => {
    if (authResult && !authResult.error) {
      /** handle successful authorization */
      void run();
    } else {
      /** handle authorization error */
    }
  });

  async function run() {
    /** Gets information about a location. */
    await gapi.client.cloudlocationfinder.projects.locations.get({
      name: 'Test string',
    });
    /** Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other project-specific locations enabled for the project. For gRPC and client library implementations, the resource name is passed as the `name` field. For direct service calls, the resource name is incorporated into the request path based on the specific service implementation and version. */
    await gapi.client.cloudlocationfinder.projects.locations.list({
      extraLocationTypes: 'Test string',
      filter: 'Test string',
      name: 'Test string',
      pageSize: 42,
      pageToken: 'Test string',
    });
    /** Retrieves a resource containing information about a cloud location. */
    await gapi.client.cloudlocationfinder.projects.locations.cloudLocations.get(
      {
        name: 'Test string',
      },
    );
    /** Lists cloud locations under a given project and location. */
    await gapi.client.cloudlocationfinder.projects.locations.cloudLocations.list(
      {
        filter: 'Test string',
        pageSize: 42,
        pageToken: 'Test string',
        parent: 'Test string',
      },
    );
    /** Searches for cloud locations from a given source location. */
    await gapi.client.cloudlocationfinder.projects.locations.cloudLocations.search(
      {
        pageSize: 42,
        pageToken: 'Test string',
        parent: 'Test string',
        query: 'Test string',
        sourceCloudLocation: 'Test string',
      },
    );
  }
});
