/* This is stub file for gapi.client.spanner-v1 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20220902

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://spanner.googleapis.com/$discovery/rest?version=v1');
    /** now we can use gapi.client.spanner */

    /** don't forget to authenticate your client before sending any request to resources: */
    /** declare client_id registered in Google Developers Console */
    const client_id = '<<PUT YOUR CLIENT ID HERE>>';
    const scope = [
        /** See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account. */
        'https://www.googleapis.com/auth/cloud-platform',
        /** Administer your Spanner databases */
        'https://www.googleapis.com/auth/spanner.admin',
        /** View and manage the contents of your Spanner databases */
        'https://www.googleapis.com/auth/spanner.data',
    ];
    const immediate = false;
    gapi.auth.authorize({ client_id, scope, immediate }, authResult => {
        if (authResult && !authResult.error) {
            /** handle successful authorization */
            run();
        } else {
            /** handle authorization error */
        }
    });

    async function run() {
        /** Gets information about a particular instance configuration. */
        await gapi.client.spanner.projects.instanceConfigs.get({
            name: "Test string",
        });
        /** Lists the supported instance configurations for a given project. */
        await gapi.client.spanner.projects.instanceConfigs.list({
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this
         * method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation
         * completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of
         * 1, corresponding to `Code.CANCELLED`.
         */
        await gapi.client.spanner.projects.instanceConfigs.operations.cancel({
            name: "Test string",
        });
        /**
         * Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support
         * this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
         */
        await gapi.client.spanner.projects.instanceConfigs.operations.delete({
            name: "Test string",
        });
        /** Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. */
        await gapi.client.spanner.projects.instanceConfigs.operations.get({
            name: "Test string",
        });
        /**
         * Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to
         * override the binding to use different resource name schemes, such as `users/*‍/operations`. To override the binding, API services can add a binding such as
         * `"/v1/{name=users/*}/operations"` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must
         * ensure the name binding is the parent resource, without the operations collection id.
         */
        await gapi.client.spanner.projects.instanceConfigs.operations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /**
         * Creates an instance and begins preparing it to begin serving. The returned long-running operation can be used to track the progress of preparing the new instance. The instance name is
         * assigned by the caller. If the named instance already exists, `CreateInstance` returns `ALREADY_EXISTS`. Immediately upon completion of this request: * The instance is readable via the
         * API, with all requested attributes but no allocated resources. Its state is `CREATING`. Until completion of the returned operation: * Cancelling the operation renders the instance
         * immediately unreadable via the API. * The instance can be deleted. * All other attempts to modify the instance are rejected. Upon completion of the returned operation: * Billing for all
         * successfully-allocated resources begins (some types may have lower than the requested levels). * Databases can be created in the instance. * The instance's allocated resource levels are
         * readable via the API. * The instance's state becomes `READY`. The returned long-running operation will have a name of the format `/operations/` and can be used to track creation of the
         * instance. The metadata field type is CreateInstanceMetadata. The response field type is Instance, if successful.
         */
        await gapi.client.spanner.projects.instances.create({
            parent: "Test string",
        }, {
            instance: {
                config: "Test string",
                createTime: "Test string",
                displayName: "Test string",
                endpointUris: [
                    "Test string"
                ],
                freeInstanceMetadata: {
                    expireBehavior: "Test string",
                    expireTime: "Test string",
                    upgradeTime: "Test string",
                },
                instanceType: "Test string",
                labels: {
                    A: "Test string"
                },
                name: "Test string",
                nodeCount: 42,
                processingUnits: 42,
                state: "Test string",
                updateTime: "Test string",
            },
            instanceId: "Test string",
        });
        /**
         * Deletes an instance. Immediately upon completion of the request: * Billing ceases for all of the instance's reserved resources. Soon afterward: * The instance and *all of its databases*
         * immediately and irrevocably disappear from the API. All data in the databases is permanently deleted.
         */
        await gapi.client.spanner.projects.instances.delete({
            name: "Test string",
        });
        /** Gets information about a particular instance. */
        await gapi.client.spanner.projects.instances.get({
            fieldMask: "Test string",
            name: "Test string",
        });
        /**
         * Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set. Authorization requires
         * `spanner.instances.getIamPolicy` on resource.
         */
        await gapi.client.spanner.projects.instances.getIamPolicy({
            resource: "Test string",
        }, {
            options: {
                requestedPolicyVersion: 42,
            },
        });
        /** Lists all instances in the given project. */
        await gapi.client.spanner.projects.instances.list({
            filter: "Test string",
            instanceDeadline: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Updates an instance, and begins allocating or releasing resources as requested. The returned long-running operation can be used to track the progress of updating the instance. If the
         * named instance does not exist, returns `NOT_FOUND`. Immediately upon completion of this request: * For resource types for which a decrease in the instance's allocation has been
         * requested, billing is based on the newly-requested level. Until completion of the returned operation: * Cancelling the operation sets its metadata's cancel_time, and begins restoring
         * resources to their pre-request values. The operation is guaranteed to succeed at undoing all resource changes, after which point it terminates with a `CANCELLED` status. * All other
         * attempts to modify the instance are rejected. * Reading the instance via the API continues to give the pre-request resource levels. Upon completion of the returned operation: * Billing
         * begins for all successfully-allocated resources (some types may have lower than the requested levels). * All newly-reserved resources are available for serving the instance's tables. *
         * The instance's new resource levels are readable via the API. The returned long-running operation will have a name of the format `/operations/` and can be used to track the instance
         * modification. The metadata field type is UpdateInstanceMetadata. The response field type is Instance, if successful. Authorization requires `spanner.instances.update` permission on the
         * resource name.
         */
        await gapi.client.spanner.projects.instances.patch({
            name: "Test string",
        }, {
            fieldMask: "Test string",
            instance: {
                config: "Test string",
                createTime: "Test string",
                displayName: "Test string",
                endpointUris: [
                    "Test string"
                ],
                freeInstanceMetadata: {
                    expireBehavior: "Test string",
                    expireTime: "Test string",
                    upgradeTime: "Test string",
                },
                instanceType: "Test string",
                labels: {
                    A: "Test string"
                },
                name: "Test string",
                nodeCount: 42,
                processingUnits: 42,
                state: "Test string",
                updateTime: "Test string",
            },
        });
        /** Sets the access control policy on an instance resource. Replaces any existing policy. Authorization requires `spanner.instances.setIamPolicy` on resource. */
        await gapi.client.spanner.projects.instances.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
        });
        /**
         * Returns permissions that the caller has on the specified instance resource. Attempting this RPC on a non-existent Cloud Spanner instance resource will result in a NOT_FOUND error if the
         * user has `spanner.instances.list` permission on the containing Google Cloud Project. Otherwise returns an empty set of permissions.
         */
        await gapi.client.spanner.projects.instances.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /**
         * Lists the backup long-running operations in the given instance. A backup operation has a name of the form `projects//instances//backups//operations/`. The long-running operation
         * metadata field type `metadata.type_url` describes the type of the metadata. Operations returned include those that have completed/failed/canceled within the last 7 days, and pending
         * operations. Operations returned are ordered by `operation.metadata.value.progress.start_time` in descending order starting from the most recently started operation.
         */
        await gapi.client.spanner.projects.instances.backupOperations.list({
            filter: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Starts copying a Cloud Spanner Backup. The returned backup long-running operation will have a name of the format `projects//instances//backups//operations/` and can be used to track
         * copying of the backup. The operation is associated with the destination backup. The metadata field type is CopyBackupMetadata. The response field type is Backup, if successful.
         * Cancelling the returned operation will stop the copying and delete the backup. Concurrent CopyBackup requests can run on the same source backup.
         */
        await gapi.client.spanner.projects.instances.backups.copy({
            parent: "Test string",
        }, {
            backupId: "Test string",
            encryptionConfig: {
                encryptionType: "Test string",
                kmsKeyName: "Test string",
            },
            expireTime: "Test string",
            sourceBackup: "Test string",
        });
        /**
         * Starts creating a new Cloud Spanner Backup. The returned backup long-running operation will have a name of the format `projects//instances//backups//operations/` and can be used to
         * track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation
         * and delete the backup. There can be only one pending backup creation per database. Backup creation of different databases can run concurrently.
         */
        await gapi.client.spanner.projects.instances.backups.create({
            backupId: "Test string",
            "encryptionConfig.encryptionType": "Test string",
            "encryptionConfig.kmsKeyName": "Test string",
            parent: "Test string",
        }, {
            createTime: "Test string",
            database: "Test string",
            databaseDialect: "Test string",
            encryptionInfo: {
                encryptionStatus: {
                    code: 42,
                    details: [
                        {
                            A: 42
                        }
                    ],
                    message: "Test string",
                },
                encryptionType: "Test string",
                kmsKeyVersion: "Test string",
            },
            expireTime: "Test string",
            maxExpireTime: "Test string",
            name: "Test string",
            referencingBackups: [
                "Test string"
            ],
            referencingDatabases: [
                "Test string"
            ],
            sizeBytes: "Test string",
            state: "Test string",
            versionTime: "Test string",
        });
        /** Deletes a pending or completed Backup. */
        await gapi.client.spanner.projects.instances.backups.delete({
            name: "Test string",
        });
        /** Gets metadata on a pending or completed Backup. */
        await gapi.client.spanner.projects.instances.backups.get({
            name: "Test string",
        });
        /**
         * Gets the access control policy for a database or backup resource. Returns an empty policy if a database or backup exists but does not have a policy set. Authorization requires
         * `spanner.databases.getIamPolicy` permission on resource. For backups, authorization requires `spanner.backups.getIamPolicy` permission on resource.
         */
        await gapi.client.spanner.projects.instances.backups.getIamPolicy({
            resource: "Test string",
        }, {
            options: {
                requestedPolicyVersion: 42,
            },
        });
        /** Lists completed and pending backups. Backups returned are ordered by `create_time` in descending order, starting from the most recent `create_time`. */
        await gapi.client.spanner.projects.instances.backups.list({
            filter: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /** Updates a pending or completed Backup. */
        await gapi.client.spanner.projects.instances.backups.patch({
            name: "Test string",
            updateMask: "Test string",
        }, {
            createTime: "Test string",
            database: "Test string",
            databaseDialect: "Test string",
            encryptionInfo: {
                encryptionStatus: {
                    code: 42,
                    details: [
                        {
                            A: 42
                        }
                    ],
                    message: "Test string",
                },
                encryptionType: "Test string",
                kmsKeyVersion: "Test string",
            },
            expireTime: "Test string",
            maxExpireTime: "Test string",
            name: "Test string",
            referencingBackups: [
                "Test string"
            ],
            referencingDatabases: [
                "Test string"
            ],
            sizeBytes: "Test string",
            state: "Test string",
            versionTime: "Test string",
        });
        /**
         * Sets the access control policy on a database or backup resource. Replaces any existing policy. Authorization requires `spanner.databases.setIamPolicy` permission on resource. For
         * backups, authorization requires `spanner.backups.setIamPolicy` permission on resource.
         */
        await gapi.client.spanner.projects.instances.backups.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
        });
        /**
         * Returns permissions that the caller has on the specified database or backup resource. Attempting this RPC on a non-existent Cloud Spanner database will result in a NOT_FOUND error if
         * the user has `spanner.databases.list` permission on the containing Cloud Spanner instance. Otherwise returns an empty set of permissions. Calling this method on a backup that does not
         * exist will result in a NOT_FOUND error if the user has `spanner.backups.list` permission on the containing instance.
         */
        await gapi.client.spanner.projects.instances.backups.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /**
         * Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this
         * method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation
         * completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of
         * 1, corresponding to `Code.CANCELLED`.
         */
        await gapi.client.spanner.projects.instances.backups.operations.cancel({
            name: "Test string",
        });
        /**
         * Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support
         * this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
         */
        await gapi.client.spanner.projects.instances.backups.operations.delete({
            name: "Test string",
        });
        /** Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. */
        await gapi.client.spanner.projects.instances.backups.operations.get({
            name: "Test string",
        });
        /**
         * Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to
         * override the binding to use different resource name schemes, such as `users/*‍/operations`. To override the binding, API services can add a binding such as
         * `"/v1/{name=users/*}/operations"` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must
         * ensure the name binding is the parent resource, without the operations collection id.
         */
        await gapi.client.spanner.projects.instances.backups.operations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /**
         * Lists database longrunning-operations. A database operation has a name of the form `projects//instances//databases//operations/`. The long-running operation metadata field type
         * `metadata.type_url` describes the type of the metadata. Operations returned include those that have completed/failed/canceled within the last 7 days, and pending operations.
         */
        await gapi.client.spanner.projects.instances.databaseOperations.list({
            filter: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Creates a new Cloud Spanner database and starts to prepare it for serving. The returned long-running operation will have a name of the format `/operations/` and can be used to track
         * preparation of the database. The metadata field type is CreateDatabaseMetadata. The response field type is Database, if successful.
         */
        await gapi.client.spanner.projects.instances.databases.create({
            parent: "Test string",
        }, {
            createStatement: "Test string",
            databaseDialect: "Test string",
            encryptionConfig: {
                kmsKeyName: "Test string",
            },
            extraStatements: [
                "Test string"
            ],
        });
        /**
         * Drops (aka deletes) a Cloud Spanner database. Completed backups for the database will be retained according to their `expire_time`. Note: Cloud Spanner might continue to accept requests
         * for a few seconds after the database has been deleted.
         */
        await gapi.client.spanner.projects.instances.databases.dropDatabase({
            database: "Test string",
        });
        /** Gets the state of a Cloud Spanner database. */
        await gapi.client.spanner.projects.instances.databases.get({
            name: "Test string",
        });
        /** Returns the schema of a Cloud Spanner database as a list of formatted DDL statements. This method does not show pending schema updates, those may be queried using the Operations API. */
        await gapi.client.spanner.projects.instances.databases.getDdl({
            database: "Test string",
        });
        /**
         * Gets the access control policy for a database or backup resource. Returns an empty policy if a database or backup exists but does not have a policy set. Authorization requires
         * `spanner.databases.getIamPolicy` permission on resource. For backups, authorization requires `spanner.backups.getIamPolicy` permission on resource.
         */
        await gapi.client.spanner.projects.instances.databases.getIamPolicy({
            resource: "Test string",
        }, {
            options: {
                requestedPolicyVersion: 42,
            },
        });
        /** Request a specific scan with Database-specific data for Cloud Key Visualizer. */
        await gapi.client.spanner.projects.instances.databases.getScans({
            endTime: "Test string",
            name: "Test string",
            startTime: "Test string",
            view: "Test string",
        });
        /** Lists Cloud Spanner databases. */
        await gapi.client.spanner.projects.instances.databases.list({
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Create a new database by restoring from a completed backup. The new database must be in the same project and in an instance with the same instance configuration as the instance
         * containing the backup. The returned database long-running operation has a name of the format `projects//instances//databases//operations/`, and can be used to track the progress of the
         * operation, and to cancel it. The metadata field type is RestoreDatabaseMetadata. The response type is Database, if successful. Cancelling the returned operation will stop the restore
         * and delete the database. There can be only one database being restored into an instance at a time. Once the restore operation completes, a new restore operation can be initiated,
         * without waiting for the optimize operation associated with the first restore to complete.
         */
        await gapi.client.spanner.projects.instances.databases.restore({
            parent: "Test string",
        }, {
            backup: "Test string",
            databaseId: "Test string",
            encryptionConfig: {
                encryptionType: "Test string",
                kmsKeyName: "Test string",
            },
        });
        /**
         * Sets the access control policy on a database or backup resource. Replaces any existing policy. Authorization requires `spanner.databases.setIamPolicy` permission on resource. For
         * backups, authorization requires `spanner.backups.setIamPolicy` permission on resource.
         */
        await gapi.client.spanner.projects.instances.databases.setIamPolicy({
            resource: "Test string",
        }, {
            policy: {
                bindings: [
                    {
                        condition: {
                            description: "Test string",
                            expression: "Test string",
                            location: "Test string",
                            title: "Test string",
                        },
                        members: [
                            "Test string"
                        ],
                        role: "Test string",
                    }
                ],
                etag: "Test string",
                version: 42,
            },
        });
        /**
         * Returns permissions that the caller has on the specified database or backup resource. Attempting this RPC on a non-existent Cloud Spanner database will result in a NOT_FOUND error if
         * the user has `spanner.databases.list` permission on the containing Cloud Spanner instance. Otherwise returns an empty set of permissions. Calling this method on a backup that does not
         * exist will result in a NOT_FOUND error if the user has `spanner.backups.list` permission on the containing instance.
         */
        await gapi.client.spanner.projects.instances.databases.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /**
         * Updates the schema of a Cloud Spanner database by creating/altering/dropping tables, columns, indexes, etc. The returned long-running operation will have a name of the format
         * `/operations/` and can be used to track execution of the schema change(s). The metadata field type is UpdateDatabaseDdlMetadata. The operation has no response.
         */
        await gapi.client.spanner.projects.instances.databases.updateDdl({
            database: "Test string",
        }, {
            operationId: "Test string",
            statements: [
                "Test string"
            ],
        });
        /** Lists Cloud Spanner database roles. */
        await gapi.client.spanner.projects.instances.databases.databaseRoles.list({
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
        });
        /**
         * Returns permissions that the caller has on the specified database or backup resource. Attempting this RPC on a non-existent Cloud Spanner database will result in a NOT_FOUND error if
         * the user has `spanner.databases.list` permission on the containing Cloud Spanner instance. Otherwise returns an empty set of permissions. Calling this method on a backup that does not
         * exist will result in a NOT_FOUND error if the user has `spanner.backups.list` permission on the containing instance.
         */
        await gapi.client.spanner.projects.instances.databases.databaseRoles.testIamPermissions({
            resource: "Test string",
        }, {
            permissions: [
                "Test string"
            ],
        });
        /**
         * Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this
         * method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation
         * completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of
         * 1, corresponding to `Code.CANCELLED`.
         */
        await gapi.client.spanner.projects.instances.databases.operations.cancel({
            name: "Test string",
        });
        /**
         * Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support
         * this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
         */
        await gapi.client.spanner.projects.instances.databases.operations.delete({
            name: "Test string",
        });
        /** Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. */
        await gapi.client.spanner.projects.instances.databases.operations.get({
            name: "Test string",
        });
        /**
         * Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to
         * override the binding to use different resource name schemes, such as `users/*‍/operations`. To override the binding, API services can add a binding such as
         * `"/v1/{name=users/*}/operations"` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must
         * ensure the name binding is the parent resource, without the operations collection id.
         */
        await gapi.client.spanner.projects.instances.databases.operations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /** Creates multiple new sessions. This API can be used to initialize a session cache on the clients. See https://goo.gl/TgSFN2 for best practices on session cache management. */
        await gapi.client.spanner.projects.instances.databases.sessions.batchCreate({
            database: "Test string",
        }, {
            sessionCount: 42,
            sessionTemplate: {
                approximateLastUseTime: "Test string",
                createTime: "Test string",
                creatorRole: "Test string",
                labels: {
                    A: "Test string"
                },
                name: "Test string",
            },
        });
        /** Begins a new transaction. This step can often be skipped: Read, ExecuteSql and Commit can begin a new transaction as a side-effect. */
        await gapi.client.spanner.projects.instances.databases.sessions.beginTransaction({
            session: "Test string",
        }, {
            options: {
                partitionedDml: {
                },
                readOnly: {
                    exactStaleness: "Test string",
                    maxStaleness: "Test string",
                    minReadTimestamp: "Test string",
                    readTimestamp: "Test string",
                    returnReadTimestamp: true,
                    strong: true,
                },
                readWrite: {
                },
            },
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
        });
        /**
         * Commits a transaction. The request includes the mutations to be applied to rows in the database. `Commit` might return an `ABORTED` error. This can occur at any time; commonly, the
         * cause is conflicts with concurrent transactions. However, it can also happen for a variety of other reasons. If `Commit` returns `ABORTED`, the caller should re-attempt the transaction
         * from the beginning, re-using the same session. On very rare occasions, `Commit` might return `UNKNOWN`. This can happen, for example, if the client job experiences a 1+ hour networking
         * failure. At that point, Cloud Spanner has lost track of the transaction outcome and we recommend that you perform another read from the database to see the state of things as they are
         * now.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.commit({
            session: "Test string",
        }, {
            mutations: [
                {
                    delete: {
                        keySet: {
                            all: true,
                            keys: [
                                [
                                    42
                                ]
                            ],
                            ranges: [
                                {
                                    endClosed: [
                                        42
                                    ],
                                    endOpen: [
                                        42
                                    ],
                                    startClosed: [
                                        42
                                    ],
                                    startOpen: [
                                        42
                                    ],
                                }
                            ],
                        },
                        table: "Test string",
                    },
                    insert: {
                        columns: [
                            "Test string"
                        ],
                        table: "Test string",
                        values: [
                            [
                                42
                            ]
                        ],
                    },
                    insertOrUpdate: {
                        columns: [
                            "Test string"
                        ],
                        table: "Test string",
                        values: [
                            [
                                42
                            ]
                        ],
                    },
                    replace: {
                        columns: [
                            "Test string"
                        ],
                        table: "Test string",
                        values: [
                            [
                                42
                            ]
                        ],
                    },
                    update: {
                        columns: [
                            "Test string"
                        ],
                        table: "Test string",
                        values: [
                            [
                                42
                            ]
                        ],
                    },
                }
            ],
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            returnCommitStats: true,
            singleUseTransaction: {
                partitionedDml: {
                },
                readOnly: {
                    exactStaleness: "Test string",
                    maxStaleness: "Test string",
                    minReadTimestamp: "Test string",
                    readTimestamp: "Test string",
                    returnReadTimestamp: true,
                    strong: true,
                },
                readWrite: {
                },
            },
            transactionId: "Test string",
        });
        /**
         * Creates a new session. A session can be used to perform transactions that read and/or modify data in a Cloud Spanner database. Sessions are meant to be reused for many consecutive
         * transactions. Sessions can only execute one transaction at a time. To execute multiple concurrent read-write/write-only transactions, create multiple sessions. Note that standalone
         * reads and queries use a transaction internally, and count toward the one transaction limit. Active sessions use additional server resources, so it is a good idea to delete idle and
         * unneeded sessions. Aside from explicit deletes, Cloud Spanner may delete sessions for which no operations are sent for more than an hour. If a session is deleted, requests to it return
         * `NOT_FOUND`. Idle sessions can be kept alive by sending a trivial SQL query periodically, e.g., `"SELECT 1"`.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.create({
            database: "Test string",
        }, {
            session: {
                approximateLastUseTime: "Test string",
                createTime: "Test string",
                creatorRole: "Test string",
                labels: {
                    A: "Test string"
                },
                name: "Test string",
            },
        });
        /** Ends a session, releasing server resources associated with it. This will asynchronously trigger cancellation of any operations that are running with this session. */
        await gapi.client.spanner.projects.instances.databases.sessions.delete({
            name: "Test string",
        });
        /**
         * Executes a batch of SQL DML statements. This method allows many statements to be run with lower latency than submitting them sequentially with ExecuteSql. Statements are executed in
         * sequential order. A request can succeed even if a statement fails. The ExecuteBatchDmlResponse.status field in the response provides information about the statement that failed. Clients
         * must inspect this field to determine whether an error occurred. Execution stops after the first failed statement; the remaining statements are not executed.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.executeBatchDml({
            session: "Test string",
        }, {
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            seqno: "Test string",
            statements: [
                {
                    params: {
                        A: 42
                    },
                    paramTypes: {
                        A: {
                            arrayElementType: undefined,
                            code: "Test string",
                            structType: {
                                fields: [
                                    {
                                        name: "Test string",
                                        type: undefined,
                                    }
                                ],
                            },
                            typeAnnotation: "Test string",
                        }
                    },
                    sql: "Test string",
                }
            ],
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Executes an SQL statement, returning all results in a single reply. This method cannot be used to return a result set larger than 10 MiB; if the query yields more data than that, the
         * query fails with a `FAILED_PRECONDITION` error. Operations inside read-write transactions might return `ABORTED`. If this occurs, the application should restart the transaction from the
         * beginning. See Transaction for more details. Larger result sets can be fetched in streaming fashion by calling ExecuteStreamingSql instead.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.executeSql({
            session: "Test string",
        }, {
            params: {
                A: 42
            },
            paramTypes: {
                A: {
                    arrayElementType: undefined,
                    code: "Test string",
                    structType: {
                        fields: [
                            {
                                name: "Test string",
                                type: undefined,
                            }
                        ],
                    },
                    typeAnnotation: "Test string",
                }
            },
            partitionToken: "Test string",
            queryMode: "Test string",
            queryOptions: {
                optimizerStatisticsPackage: "Test string",
                optimizerVersion: "Test string",
            },
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            resumeToken: "Test string",
            seqno: "Test string",
            sql: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Like ExecuteSql, except returns the result set as a stream. Unlike ExecuteSql, there is no limit on the size of the returned result set. However, no individual row in the result set can
         * exceed 100 MiB, and no column value can exceed 10 MiB.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.executeStreamingSql({
            session: "Test string",
        }, {
            params: {
                A: 42
            },
            paramTypes: {
                A: {
                    arrayElementType: undefined,
                    code: "Test string",
                    structType: {
                        fields: [
                            {
                                name: "Test string",
                                type: undefined,
                            }
                        ],
                    },
                    typeAnnotation: "Test string",
                }
            },
            partitionToken: "Test string",
            queryMode: "Test string",
            queryOptions: {
                optimizerStatisticsPackage: "Test string",
                optimizerVersion: "Test string",
            },
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            resumeToken: "Test string",
            seqno: "Test string",
            sql: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /** Gets a session. Returns `NOT_FOUND` if the session does not exist. This is mainly useful for determining whether a session is still alive. */
        await gapi.client.spanner.projects.instances.databases.sessions.get({
            name: "Test string",
        });
        /** Lists all sessions in a given database. */
        await gapi.client.spanner.projects.instances.databases.sessions.list({
            database: "Test string",
            filter: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /**
         * Creates a set of partition tokens that can be used to execute a query operation in parallel. Each of the returned partition tokens can be used by ExecuteStreamingSql to specify a subset
         * of the query result to read. The same session and read-only transaction must be used by the PartitionQueryRequest used to create the partition tokens and the ExecuteSqlRequests that use
         * the partition tokens. Partition tokens become invalid when the session used to create them is deleted, is idle for too long, begins a new transaction, or becomes too old. When any of
         * these happen, it is not possible to resume the query, and the whole operation must be restarted from the beginning.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.partitionQuery({
            session: "Test string",
        }, {
            params: {
                A: 42
            },
            paramTypes: {
                A: {
                    arrayElementType: undefined,
                    code: "Test string",
                    structType: {
                        fields: [
                            {
                                name: "Test string",
                                type: undefined,
                            }
                        ],
                    },
                    typeAnnotation: "Test string",
                }
            },
            partitionOptions: {
                maxPartitions: "Test string",
                partitionSizeBytes: "Test string",
            },
            sql: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Creates a set of partition tokens that can be used to execute a read operation in parallel. Each of the returned partition tokens can be used by StreamingRead to specify a subset of the
         * read result to read. The same session and read-only transaction must be used by the PartitionReadRequest used to create the partition tokens and the ReadRequests that use the partition
         * tokens. There are no ordering guarantees on rows returned among the returned partition tokens, or even within each individual StreamingRead call issued with a partition_token. Partition
         * tokens become invalid when the session used to create them is deleted, is idle for too long, begins a new transaction, or becomes too old. When any of these happen, it is not possible
         * to resume the read, and the whole operation must be restarted from the beginning.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.partitionRead({
            session: "Test string",
        }, {
            columns: [
                "Test string"
            ],
            index: "Test string",
            keySet: {
                all: true,
                keys: [
                    [
                        42
                    ]
                ],
                ranges: [
                    {
                        endClosed: [
                            42
                        ],
                        endOpen: [
                            42
                        ],
                        startClosed: [
                            42
                        ],
                        startOpen: [
                            42
                        ],
                    }
                ],
            },
            partitionOptions: {
                maxPartitions: "Test string",
                partitionSizeBytes: "Test string",
            },
            table: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Reads rows from the database using key lookups and scans, as a simple key/value style alternative to ExecuteSql. This method cannot be used to return a result set larger than 10 MiB; if
         * the read matches more data than that, the read fails with a `FAILED_PRECONDITION` error. Reads inside read-write transactions might return `ABORTED`. If this occurs, the application
         * should restart the transaction from the beginning. See Transaction for more details. Larger result sets can be yielded in streaming fashion by calling StreamingRead instead.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.read({
            session: "Test string",
        }, {
            columns: [
                "Test string"
            ],
            index: "Test string",
            keySet: {
                all: true,
                keys: [
                    [
                        42
                    ]
                ],
                ranges: [
                    {
                        endClosed: [
                            42
                        ],
                        endOpen: [
                            42
                        ],
                        startClosed: [
                            42
                        ],
                        startOpen: [
                            42
                        ],
                    }
                ],
            },
            limit: "Test string",
            partitionToken: "Test string",
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            resumeToken: "Test string",
            table: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Rolls back a transaction, releasing any locks it holds. It is a good idea to call this for any transaction that includes one or more Read or ExecuteSql requests and ultimately decides
         * not to commit. `Rollback` returns `OK` if it successfully aborts the transaction, the transaction was already aborted, or the transaction is not found. `Rollback` never returns
         * `ABORTED`.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.rollback({
            session: "Test string",
        }, {
            transactionId: "Test string",
        });
        /**
         * Like Read, except returns the result set as a stream. Unlike Read, there is no limit on the size of the returned result set. However, no individual row in the result set can exceed 100
         * MiB, and no column value can exceed 10 MiB.
         */
        await gapi.client.spanner.projects.instances.databases.sessions.streamingRead({
            session: "Test string",
        }, {
            columns: [
                "Test string"
            ],
            index: "Test string",
            keySet: {
                all: true,
                keys: [
                    [
                        42
                    ]
                ],
                ranges: [
                    {
                        endClosed: [
                            42
                        ],
                        endOpen: [
                            42
                        ],
                        startClosed: [
                            42
                        ],
                        startOpen: [
                            42
                        ],
                    }
                ],
            },
            limit: "Test string",
            partitionToken: "Test string",
            requestOptions: {
                priority: "Test string",
                requestTag: "Test string",
                transactionTag: "Test string",
            },
            resumeToken: "Test string",
            table: "Test string",
            transaction: {
                begin: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
                id: "Test string",
                singleUse: {
                    partitionedDml: {
                    },
                    readOnly: {
                        exactStaleness: "Test string",
                        maxStaleness: "Test string",
                        minReadTimestamp: "Test string",
                        readTimestamp: "Test string",
                        returnReadTimestamp: true,
                        strong: true,
                    },
                    readWrite: {
                    },
                },
            },
        });
        /**
         * Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this
         * method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation
         * completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of
         * 1, corresponding to `Code.CANCELLED`.
         */
        await gapi.client.spanner.projects.instances.operations.cancel({
            name: "Test string",
        });
        /**
         * Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support
         * this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
         */
        await gapi.client.spanner.projects.instances.operations.delete({
            name: "Test string",
        });
        /** Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. */
        await gapi.client.spanner.projects.instances.operations.get({
            name: "Test string",
        });
        /**
         * Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to
         * override the binding to use different resource name schemes, such as `users/*‍/operations`. To override the binding, API services can add a binding such as
         * `"/v1/{name=users/*}/operations"` to their service configuration. For backwards compatibility, the default name includes the operations collection id, however overriding users must
         * ensure the name binding is the parent resource, without the operations collection id.
         */
        await gapi.client.spanner.projects.instances.operations.list({
            filter: "Test string",
            name: "Test string",
            pageSize: 42,
            pageToken: "Test string",
        });
        /** Return available scans given a Database-specific resource name. */
        await gapi.client.spanner.scans.list({
            filter: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            parent: "Test string",
            view: "Test string",
        });
    }
});
