/* This is stub file for gapi.client.fitness-v1 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20220823

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://fitness.googleapis.com/$discovery/rest?version=v1');
    /** now we can use gapi.client.fitness */

    /** don't forget to authenticate your client before sending any request to resources: */
    /** declare client_id registered in Google Developers Console */
    const client_id = '<<PUT YOUR CLIENT ID HERE>>';
    const scope = [
        /** Use Google Fit to see and store your physical activity data */
        'https://www.googleapis.com/auth/fitness.activity.read',
        /** Add to your Google Fit physical activity data */
        'https://www.googleapis.com/auth/fitness.activity.write',
        /** See info about your blood glucose in Google Fit. I consent to Google sharing my blood glucose information with this app. */
        'https://www.googleapis.com/auth/fitness.blood_glucose.read',
        /** Add info about your blood glucose to Google Fit. I consent to Google using my blood glucose information with this app. */
        'https://www.googleapis.com/auth/fitness.blood_glucose.write',
        /** See info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app. */
        'https://www.googleapis.com/auth/fitness.blood_pressure.read',
        /** Add info about your blood pressure in Google Fit. I consent to Google using my blood pressure information with this app. */
        'https://www.googleapis.com/auth/fitness.blood_pressure.write',
        /** See info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app. */
        'https://www.googleapis.com/auth/fitness.body_temperature.read',
        /** Add to info about your body temperature in Google Fit. I consent to Google using my body temperature information with this app. */
        'https://www.googleapis.com/auth/fitness.body_temperature.write',
        /** See info about your body measurements in Google Fit */
        'https://www.googleapis.com/auth/fitness.body.read',
        /** Add info about your body measurements to Google Fit */
        'https://www.googleapis.com/auth/fitness.body.write',
        /** See your heart rate data in Google Fit. I consent to Google sharing my heart rate information with this app. */
        'https://www.googleapis.com/auth/fitness.heart_rate.read',
        /** Add to your heart rate data in Google Fit. I consent to Google using my heart rate information with this app. */
        'https://www.googleapis.com/auth/fitness.heart_rate.write',
        /** See your Google Fit speed and distance data */
        'https://www.googleapis.com/auth/fitness.location.read',
        /** Add to your Google Fit location data */
        'https://www.googleapis.com/auth/fitness.location.write',
        /** See info about your nutrition in Google Fit */
        'https://www.googleapis.com/auth/fitness.nutrition.read',
        /** Add to info about your nutrition in Google Fit */
        'https://www.googleapis.com/auth/fitness.nutrition.write',
        /** See info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app. */
        'https://www.googleapis.com/auth/fitness.oxygen_saturation.read',
        /** Add info about your oxygen saturation in Google Fit. I consent to Google using my oxygen saturation information with this app. */
        'https://www.googleapis.com/auth/fitness.oxygen_saturation.write',
        /** See info about your reproductive health in Google Fit. I consent to Google sharing my reproductive health information with this app. */
        'https://www.googleapis.com/auth/fitness.reproductive_health.read',
        /** Add info about your reproductive health in Google Fit. I consent to Google using my reproductive health information with this app. */
        'https://www.googleapis.com/auth/fitness.reproductive_health.write',
        /** See your sleep data in Google Fit. I consent to Google sharing my sleep information with this app. */
        'https://www.googleapis.com/auth/fitness.sleep.read',
        /** Add to your sleep data in Google Fit. I consent to Google using my sleep information with this app. */
        'https://www.googleapis.com/auth/fitness.sleep.write',
    ];
    const immediate = false;
    gapi.auth.authorize({ client_id, scope, immediate }, authResult => {
        if (authResult && !authResult.error) {
            /** handle successful authorization */
            run();
        } else {
            /** handle authorization error */
        }
    });

    async function run() {
        /**
         * Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggregated into
         * exactly one bucket type per request.
         */
        await gapi.client.fitness.users.dataset.aggregate({
            userId: "Test string",
        }, {
            aggregateBy: [
                {
                    dataSourceId: "Test string",
                    dataTypeName: "Test string",
                }
            ],
            bucketByActivitySegment: {
                activityDataSourceId: "Test string",
                minDurationMillis: "Test string",
            },
            bucketByActivityType: {
                activityDataSourceId: "Test string",
                minDurationMillis: "Test string",
            },
            bucketBySession: {
                minDurationMillis: "Test string",
            },
            bucketByTime: {
                durationMillis: "Test string",
                period: {
                    timeZoneId: "Test string",
                    type: "Test string",
                    value: 42,
                },
            },
            endTimeMillis: "Test string",
            filteredDataQualityStandard: [
                "Test string"
            ],
            startTimeMillis: "Test string",
        });
        /**
         * Creates a new data source that is unique across all data sources belonging to this user. A data source is a unique source of sensor data. Data sources can expose raw data coming from
         * hardware sensors on local or companion devices. They can also expose derived data, created by transforming or merging other data sources. Multiple data sources can exist for the same
         * data type. Every data point in every dataset inserted into or read from the Fitness API has an associated data source. Each data source produces a unique stream of dataset updates, with
         * a unique data source identifier. Not all changes to data source affect the data stream ID, so that data collected by updated versions of the same application/device can still be
         * considered to belong to the same data source. Data sources are identified using a string generated by the server, based on the contents of the source being created. The dataStreamId
         * field should not be set when invoking this method. It will be automatically generated by the server with the correct format. If a dataStreamId is set, it must match the format that the
         * server would generate. This format is a combination of some fields from the data source, and has a specific order. If it doesn't match, the request will fail with an error. Specifying a
         * DataType which is not a known type (beginning with "com.google.") will create a DataSource with a *custom data type*. Custom data types are only readable by the application that created
         * them. Custom data types are *deprecated*; use standard data types instead. In addition to the data source fields included in the data source ID, the developer project number that is
         * authenticated when creating the data source is included. This developer project number is obfuscated when read by any other developer reading public data types.
         */
        await gapi.client.fitness.users.dataSources.create({
            userId: "Test string",
        }, {
            application: {
                detailsUrl: "Test string",
                name: "Test string",
                packageName: "Test string",
                version: "Test string",
            },
            dataQualityStandard: [
                "Test string"
            ],
            dataStreamId: "Test string",
            dataStreamName: "Test string",
            dataType: {
                field: [
                    {
                        format: "Test string",
                        name: "Test string",
                        optional: true,
                    }
                ],
                name: "Test string",
            },
            device: {
                manufacturer: "Test string",
                model: "Test string",
                type: "Test string",
                uid: "Test string",
                version: "Test string",
            },
            name: "Test string",
            type: "Test string",
        });
        /** Deletes the specified data source. The request will fail if the data source contains any data points. */
        await gapi.client.fitness.users.dataSources.delete({
            dataSourceId: "Test string",
            userId: "Test string",
        });
        /** Returns the specified data source. */
        await gapi.client.fitness.users.dataSources.get({
            dataSourceId: "Test string",
            userId: "Test string",
        });
        /**
         * Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to
         * other developers, or calls using other scopes.
         */
        await gapi.client.fitness.users.dataSources.list({
            dataTypeName: "Test string",
            userId: "Test string",
        });
        /**
         * Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified. Data sources are identified
         * by their dataStreamId.
         */
        await gapi.client.fitness.users.dataSources.update({
            dataSourceId: "Test string",
            userId: "Test string",
        }, {
            application: {
                detailsUrl: "Test string",
                name: "Test string",
                packageName: "Test string",
                version: "Test string",
            },
            dataQualityStandard: [
                "Test string"
            ],
            dataStreamId: "Test string",
            dataStreamName: "Test string",
            dataType: {
                field: [
                    {
                        format: "Test string",
                        name: "Test string",
                        optional: true,
                    }
                ],
                name: "Test string",
            },
            device: {
                manufacturer: "Test string",
                model: "Test string",
                type: "Test string",
                uid: "Test string",
                version: "Test string",
            },
            name: "Test string",
            type: "Test string",
        });
        /** Queries for user's data point changes for a particular data source. */
        await gapi.client.fitness.users.dataSources.dataPointChanges.list({
            dataSourceId: "Test string",
            limit: 42,
            pageToken: "Test string",
            userId: "Test string",
        });
        /**
         * Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point
         * will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only
         * the overlapping portion of the data point will be deleted.
         */
        await gapi.client.fitness.users.dataSources.datasets.delete({
            datasetId: "Test string",
            dataSourceId: "Test string",
            userId: "Test string",
        });
        /**
         * Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data
         * point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.
         */
        await gapi.client.fitness.users.dataSources.datasets.get({
            datasetId: "Test string",
            dataSourceId: "Test string",
            limit: 42,
            pageToken: "Test string",
            userId: "Test string",
        });
        /**
         * Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data
         * points can belong to more than one dataset. This method does not use patch semantics: the data points provided are merely inserted, with no existing data replaced.
         */
        await gapi.client.fitness.users.dataSources.datasets.patch({
            datasetId: "Test string",
            dataSourceId: "Test string",
            userId: "Test string",
        }, {
            dataSourceId: "Test string",
            maxEndTimeNs: "Test string",
            minStartTimeNs: "Test string",
            nextPageToken: "Test string",
            point: [
                {
                    computationTimeMillis: "Test string",
                    dataTypeName: "Test string",
                    endTimeNanos: "Test string",
                    modifiedTimeMillis: "Test string",
                    originDataSourceId: "Test string",
                    rawTimestampNanos: "Test string",
                    startTimeNanos: "Test string",
                    value: [
                        {
                            fpVal: 42,
                            intVal: 42,
                            mapVal: [
                                {
                                    key: "Test string",
                                    value: {
                                        fpVal: 42,
                                    },
                                }
                            ],
                            stringVal: "Test string",
                        }
                    ],
                }
            ],
        });
        /** Deletes a session specified by the given session ID. */
        await gapi.client.fitness.users.sessions.delete({
            sessionId: "Test string",
            userId: "Test string",
        });
        /** Lists sessions previously created. */
        await gapi.client.fitness.users.sessions.list({
            activityType: 42,
            endTime: "Test string",
            includeDeleted: true,
            pageToken: "Test string",
            startTime: "Test string",
            userId: "Test string",
        });
        /** Updates or insert a given session. */
        await gapi.client.fitness.users.sessions.update({
            sessionId: "Test string",
            userId: "Test string",
        }, {
            activeTimeMillis: "Test string",
            activityType: 42,
            application: {
                detailsUrl: "Test string",
                name: "Test string",
                packageName: "Test string",
                version: "Test string",
            },
            description: "Test string",
            endTimeMillis: "Test string",
            id: "Test string",
            modifiedTimeMillis: "Test string",
            name: "Test string",
            startTimeMillis: "Test string",
        });
    }
});
