/* This is stub file for gapi.client.drivelabels-v2 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20220817

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://drivelabels.googleapis.com/$discovery/rest?version=v2');
    /** now we can use gapi.client.drivelabels */

    run();

    async function run() {
        /**
         * Get a label by its resource name. Resource name may be any of: * `labels/{id}` - See `labels/{id}@latest` * `labels/{id}@latest` - Gets the latest revision of the label. *
         * `labels/{id}@published` - Gets the current published revision of the label. * `labels/{id}@{revision_id}` - Gets the label at the specified revision ID.
         */
        await gapi.client.drivelabels.labels.get({
            languageCode: "Test string",
            name: "Test string",
            useAdminAccess: true,
            view: "Test string",
        });
        /** List labels. */
        await gapi.client.drivelabels.labels.list({
            languageCode: "Test string",
            minimumRole: "Test string",
            pageSize: 42,
            pageToken: "Test string",
            publishedOnly: true,
            useAdminAccess: true,
            view: "Test string",
        });
    }
});
