/* This is stub file for gapi.client.cloudprofiler-v2 definition tests */
// IMPORTANT
// This file was generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
// In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator

// Revision: 20220904

gapi.load('client', async () => {
    /** now we can use gapi.client */

    await gapi.client.load('https://cloudprofiler.googleapis.com/$discovery/rest?version=v2');
    /** now we can use gapi.client.cloudprofiler */

    /** don't forget to authenticate your client before sending any request to resources: */
    /** declare client_id registered in Google Developers Console */
    const client_id = '<<PUT YOUR CLIENT ID HERE>>';
    const scope = [
        /** See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account. */
        'https://www.googleapis.com/auth/cloud-platform',
        /** View and write monitoring data for all of your Google and third-party Cloud and API projects */
        'https://www.googleapis.com/auth/monitoring',
        /** Publish metric data to your Google Cloud projects */
        'https://www.googleapis.com/auth/monitoring.write',
    ];
    const immediate = false;
    gapi.auth.authorize({ client_id, scope, immediate }, authResult => {
        if (authResult && !authResult.error) {
            /** handle successful authorization */
            run();
        } else {
            /** handle authorization error */
        }
    });

    async function run() {
        /**
         * CreateProfile creates a new profile resource in the online mode. The server ensures that the new profiles are created at a constant rate per deployment, so the creation request may hang
         * for some time until the next profile session is available. The request may fail with ABORTED error if the creation is not available within ~1m, the response will indicate the duration
         * of the backoff the client should take before attempting creating a profile again. The backoff duration is returned in google.rpc.RetryInfo extension on the response status. To a gRPC
         * client, the extension will be return as a binary-serialized proto in the trailing metadata item named "google.rpc.retryinfo-bin".
         */
        await gapi.client.cloudprofiler.projects.profiles.create({
            parent: "Test string",
        }, {
            deployment: {
                labels: {
                    A: "Test string"
                },
                projectId: "Test string",
                target: "Test string",
            },
            profileType: [
                "Test string"
            ],
        });
        /** CreateOfflineProfile creates a new profile resource in the offline mode. The client provides the profile to create along with the profile bytes, the server records it. */
        await gapi.client.cloudprofiler.projects.profiles.createOffline({
            parent: "Test string",
        }, {
            deployment: {
                labels: {
                    A: "Test string"
                },
                projectId: "Test string",
                target: "Test string",
            },
            duration: "Test string",
            labels: {
                A: "Test string"
            },
            name: "Test string",
            profileBytes: "Test string",
            profileType: "Test string",
        });
        /**
         * UpdateProfile updates the profile bytes and labels on the profile resource created in the online mode. Updating the bytes for profiles created in the offline mode is currently not
         * supported: the profile content must be provided at the time of the profile creation.
         */
        await gapi.client.cloudprofiler.projects.profiles.patch({
            name: "Test string",
            updateMask: "Test string",
        }, {
            deployment: {
                labels: {
                    A: "Test string"
                },
                projectId: "Test string",
                target: "Test string",
            },
            duration: "Test string",
            labels: {
                A: "Test string"
            },
            name: "Test string",
            profileBytes: "Test string",
            profileType: "Test string",
        });
    }
});
