name: Auto Publish to NPM

on:
  schedule:
    - cron: '0 * * * *'
  repository_dispatch:
    types: [auto-publish]
  workflow_dispatch: # for manual testing

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for NPM provenance
    steps:
      # setup
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # do the job
      - name: Auto Publish to NPM
        run: npm run auto-publish
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          NPM_PUBLISH_AUTOMATION_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION_TOKEN }}
