name: Dedupe npm packages

on:
  schedule:
    - cron: '30 3 * * 0'
  workflow_dispatch: # for manual testing

jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # do the job
      - name: Dedupe and update npm packages
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npm dedupe
            npm update
          COMMIT_MESSAGE: 'chore: dedupe and update npm dependencies'
          PR_BRANCH_NAME: 'chore-npm-dedupe-${PR_ID}'
          PR_TITLE: 'chore: dedupe and update npm dependencies'
# cspell:words technote
