name: rebase pull requests
on:
  push:
  release:
    types: [published]
jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: 'bbeesley/gha-auto-dependabot-rebase@main' # cspell:words bbeesley
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
